# Generated by Django 3.1.6 on 2021-08-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_courses', models.ManyToManyField(blank=True, related_name='courses', to='course.Course')),
            ],
        ),
    ]
