# Generated by Django 3.1.6 on 2021-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profiles.Profile'),
        ),
    ]
