# Generated by Django 3.1.6 on 2021-10-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='lectures/')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ['name'],
            },
        ),
    ]
