# Generated by Django 3.1.6 on 2021-08-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='lecture/%Y/%m/%d')),
            ],
            options={
                'db_table': 'lecture',
                'ordering': ['name'],
            },
        ),
    ]
